config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :days, only: [:index, :show] do
    resources :tasks, except: [ :index ]
  end
  resources :moods, only: [:index, :edit, :show, :update]
  get 'select_day_from_date', to: 'tasks#select_day_from_date'
  get 'all_tasks', to: 'tasks#all_tasks'
  get 'get_moods_by_date', to: 'moods#get_moods_by_date'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :user
  has_many :tasks
  has_one :mood

  validates :calendar_date, presence: true, uniqueness: { scope: :user_id }
end

app/models/mood.rb
class Mood < ApplicationRecord
  belongs_to :day
  validates :mood_notes, length: { maximum: 350 }, allow_blank: true
  validates :mood_name, presence: true
  validates :day_id, presence: true, uniqueness: true
  # validates :mood_name, :inclusion { :in => [ '😡', '😢', '😟', '😐', '🙂', '😍' ] }

  MOODS =  [ '😡', '😢', '😟', '😐', '🙂', '😍' ]
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :day
  validates :title, presence: true,  allow_blank: false, length: 3..32
  validates :day_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :days

  after_create do
    day1 = Date.new(2022, 1, 1)
    day = 0

    365.times do
      newDay = Day.create!(:calendar_date => day1 + day, :user_id => self.id )

      if newDay.save
        puts "Day #{day + 1} added"
      else
        puts "Failed"
      end

      mood = Mood.create!(day: newDay)
      if mood.save
        puts "Mood #{day + 1} added"
      else
        puts "Failed"
      end

      day = day += 1
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname])
  end

  def after_sign_in_path_for(resource)
    @current_day = Day.where(calendar_date: Date.today)
    @mood = Mood.where(day_id: @current_day, mood_name: "#")

    # raise

    if @mood.blank?
      days_path
    else
      edit_mood_path(find_mood_params)
    end

    # days_path
    # @current_day = Day.where("calendar_date == #{Date.today}")
    # # raise
    # @mood = Mood.where("day_id == #{@current_day.id}")
    # if @mood.mood_name == ''
    #   redirect_to days_path
    # else
    #   days_path
    # end
  end

  # meta url helper
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def find_mood_params
    @mood.as_json.first["id"]
  end

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  #before_action :authenticate_user, only: [:show]

  def index

    # @days = Day.all
#     @days = Day.select { |day| day.user_id == 1} # "2" should be replaced by some kind of user validation from devise.
#     @days.order(:calendar_date) # use .order (active record) bc .sort_by is ruby code and the object is and active record reference

    @days = Day.all

end

  def show
    @day = Day.find(params[:id])
    @tasks = Task.where(day: @day)
    @task = Task.new
    # @mood = Mood.find { |mood| mood.day == @day}
  end

end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController

  #Index
  def index
    @moods = Mood.all
    # instead of displaying all the moods,
    # @min_range = 1
    # @max_range = 10
    # @moods = Mood.find(@min_range..@max_range)
    # when the next page button is clicked, it should change
    # min_range and max_range to +10
    # previous button on the next page - just does the opposit of ^^ (minuses)
    # previous button hidden until we are on next poage
  end

  #New
  def new
    @mood = Mood.new
    @day = current_day
  end

  #Create
  def create
    @mood = Mood.new(mood_params)
    @day = current_day
    @mood.day = @day
    if @mood.save!
    #redirect_to day_path(@day)
    else
      #if the mood doesnt save, reload the new mood page
      render :new
    end
  end

  #Edit
  def edit
    @mood = Mood.find(params[:id])
  end

  #Update
  def update
    @mood = Mood.find(params[:id])
    @mood.update(mood_params)
    if @mood.save!
      redirect_to days_path
    else
      #if the mood doesnt save, reload the new mood page
      render :edit
    end
  end

  def get_moods_by_date
    res = ActiveRecord::Base.connection.execute("SELECT JSON_OBJECT_AGG(calendar_date, mood_name) AS all_moods FROM moods
    JOIN days ON days.id = moods.day_id
    WHERE mood_name != '#';")
    puts res.to_json()
    render json: res.to_json()
  end


  #Strong params
   private

   def mood_params
     params.require(:mood).permit(:mood_name, :mood_notes)
   end

   def current_day
     @current_day = Day.find(:calendar_date == Date.today)
   end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #before_action :authenticate_user
  def new
    @task = Task.new
    @day = selected_day
  end

  def create
    @task = Task.new(task_params)
    @day = selected_day
    @task.day = @day
    if @task.save
      redirect_to day_path(@day)
    else
      #if the task doesnt save, reload the new task page
      @tasks = Task.where(day: selected_day)
      render 'days/show'
    end
  end

  def edit
    @day = selected_day
    @task = Task.find(params[:id])
  end

  def update
    @day = selected_day
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to day_path(@day)
  end

  def destroy
    @task = Task.find(params[:id])
    @day = selected_day
    @task.destroy
    redirect_to day_path(@day)
  end

  def select_day_from_date
    @day = Day.find_by(calendar_date: params[:selected_date])
    render json: "{\"DayID\": #{@day.id}}"
  end

  def all_tasks
    # @tasks = Day.joins(:tasks)
    # @tasks.each do |d|
    #   puts d.tasks
    # end
    # render json: @tasks.to_json()

    res = ActiveRecord::Base.connection.execute("SELECT
      calendar_date,
      day_id,
      COUNT(*) AS total,
      COUNT(*) FILTER (WHERE status IS TRUE) AS total_done,
      JSON_AGG(title) AS task_titles
      FROM tasks
      JOIN days ON days.id = tasks.day_id
      GROUP BY calendar_date, day_id
      ORDER BY calendar_date")

    render json: res.to_json()
  end


  private

  def task_params
    params.require(:task).permit(:title, :status)
  end

  def selected_day
    @current_day = Day.find(params[:day_id])
  end

  def confirm_delete
    @task = Task.find(params[:id])
    @task.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/days/_task_status_form.html.erb
<%= simple_form_for [@day, task] do |f| %>
  <% if task.status == false %>
    <%= f.hidden_field :status, value: true %>
    <%= f.submit ' ', class: "task-todo" %>
  <% else %>
    <%= f.hidden_field :status, value: false %>
    <div>
      <%= button_tag type: 'submit', class: "task-done" do %>
          <i class="fas fa-check-circle"></i>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/days/index.html.erb
<%# Top Card Section  %>

<section class="days-index">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="index-welcome">
          <h1 class="welcome-message">
            Hello, Sophie &#128075;
          </h1>
          <p class="landing-desc">
            Let's start a day!
          </p>
          <div id="task-cards">

          </div>

        </div>
      </div>
    </div>
  </div>
</section>


<%# calendar Section  %>
<section id="calendar" class="index-calendar">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="calendar_container">
        <div class="calendar">
          <div class="month">
            <i class="fas fa-angle-left prev"></i>
            <div class="date">
              <h1></h1>
              <p></p>
            </div>
            <i class="fas fa-angle-right next"></i>
          </div>
          <div class="weekdays">
            <div>Sun</div>
            <div>Mon</div>
            <div>Tue</div>
            <div>Wed</div>
            <div>Thu</div>
            <div>Fri</div>
            <div>Sat</div>
          </div>
          <div class="days">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/days/show.html.erb
<div class="day-show">
  <div class="container">
    <div class="row justify-content-center">
      <div class="day-component col-lg-8 col-md-10 col-11">
      <%# "strftime" formats date according to the directives in the given format string. %>
        <h2><%= @day.calendar_date.strftime('%a, %d %b %Y') %></h2>
        <%# if @day.calendar_date == Date.today %>
          <div class="pomodoro-container">

            <%# SOPHIE'S WORK %>

            <div class="timer-container">
              <p id="time-display">0:00</p>
            </div>
            <div class="pomo-button-container">
              <button class="col-3 col-md-2" id="work-btn">Work</button>
              <button class="col-3 col-md-2" id="short-break-btn">Short Break</button>
              <button class="col-3 col-md-2" id="long-break-btn">Long Break</button>
            </div>
            <div class="spr-button-container">
              <div id="start-btn">
                <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 512 512"><title>ionicons-v5-c</title><path fill="#456fab" fill-opacity="0.5" d="M256,48C141.31,48,48,141.31,48,256s93.31,208,208,208,208-93.31,208-208S370.69,48,256,48Zm74.77,217.3L216.32,334.44A10.78,10.78,0,0,1,200,325.13V186.87a10.78,10.78,0,0,1,16.32-9.31L330.77,246.7A10.89,10.89,0,0,1,330.77,265.3Z"/></svg>
              </div>
            </div>

          </div>
        <%# end %>
        <%# ANTON'S WORK %>


        <div class="task-list" id="task-list">
          <% if @tasks.blank? %>
            <div class="task-empty-message">Add your first task of the day.</div>
          <% else %>
            <% @tasks.sort_by{ |task| task.id }.each  do |task| %>
              <div class="task-list-item" id="task-item-<%= task.id %>">
                <div class="task-status">
                  <div><%= render "days/task_status_form", task: task %></div>
                </div>
                <% if task.status == true %>
                  <div class="task-list-title disabled" id="task-title-<%= task.id %>" style="display: block">
                    <div class="task-title"><p><%= task.title %></p></div>
                  </div>
                <% else %>
                  <div class="task-list-title" id="task-title-<%= task.id %>" style="display: block">
                    <div class="task-title"><p><%= task.title %></p></div>
                  </div>
                <% end %>
                <div class="task-edit">
                  <%# <%= link_to edit_day_task_path(task.id, day_id: @day.id), class: "btn-task-edit" do %>
                    <%# <i class="fas fa-edit"></i> %>
                  <%# <% end %>
                  <div class="btn btn-task-edit" id="edit-task-<%= task.id %>" style="<%= @task.errors.messages.present? ? "display: none;" : ""%>">
                    <div onclick="hideEditTask(<%= task.id %>)"><i class="fas fa-edit"></i></div>
                  </div>
                </div>
                <div class="task-delete" id="delete-task-<%= task.id %>">
                  <%= link_to day_task_path(task.id, day_id: @day.id), class: "btn-task-delete", method: :delete do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </div>
              </div>
              <div class="hidden-edit-task" id="hidden-edit-task-<%= task.id %>" style="<%= @task.errors.messages.empty? ? "display: none;" : ""%>">
                <%= simple_form_for([@day, task], remote: true) do |f| %>
                  <%= f.input :title, input_html: { class: "task-list-title" }, label: false  %>
                  <%= button_tag type: 'submit', class: "task-done" do %>
                      <i class="far fa-check-circle"></i>
                  <% end %>
                <% end %>
              </div>
            <% end  %>
          <% end %>
          <div class="task-list-item" id="hidden-new-task" style="<%= @task.errors.messages.empty? ? "display: none;" : ""%>">
            <%= simple_form_for([@day, @task], remote: true) do |f| %>
              <%= f.input :title, input_html: { class: "task-list-title" }, label: false  %>
              <%= button_tag type: 'submit', class: "task-done" do %>
                  <i class="far fa-check-circle"></i>
              <% end %>
            <% end %>
          </div>
          <div class="btn btn-new-task cancel" id="cancel-task-btn" style="<%= @task.errors.messages.empty? ? "display: none;" : ""%>">
            <div onclick="hideNewTask()">Cancel</div>
          </div>
          <div class="btn btn-new-task" id="new-task-btn" style="<%= @task.errors.messages.present? ? "display: none;" : ""%>">
            <div onclick="hideNewTask()">Add Task</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<%# SOPHIE'S JS %>
<%# <script src="pomodoro.js"></script> %>



<%# ANTON'S JS %>

<script>
// Get the container element
// var btnContainer = document.getElementById("task-list");

// // Get all buttons with class="btn" inside the container
// var btns = btnContainer.getElementsByClassName("task-list-title");

// // Loop through the buttons and add the active class to the current/clicked button
// for (var i = 0; i < btns.length; i++) {
//   btns[i].addEventListener("click", function() {
//     var current = document.getElementsByClassName("active");

//     // If there's no active class
//     if (current.length > 0) {
//       current[0].className = current[0].className.replace(" active", "");
//     }

//     // Add the active class to the current/clicked button
//     this.className += " active";
//   });
// }

function hideNewTask() {
  const error = document.querySelector(".invalid-feedback");
  console.log(error)
  var x = document.getElementById("hidden-new-task");
  var y = document.getElementById("cancel-task-btn");
  var z = document.getElementById("new-task-btn");
  console.log(x)
  if (x.style.display === "none") {
    x.style.display = "block";
    y.style.display = "block";
    z.style.display = "none";
  } else {
    x.style.display = "none";
    y.style.display = "none";
    z.style.display = "block";
  }
}

function hideEditTask(taskID) {
  const error = document.querySelector(".invalid-feedback");
  console.log(error)
  var x = document.getElementById(`task-item-${taskID}`);
  var y = document.getElementById(`hidden-edit-task-${taskID}`);
  // var z = document.getElementById(`delete-task-${taskID}`);
  // var w = document.getElementById(`edit-task-${taskID}`);
  console.log(x)
  if (x.style.display === "none") {
    x.style.display = "block";
    y.style.display = "none";
    // z.style.display = "none";
    // w.style.display = "none";
  } else {
    x.style.display = "none";
    y.style.display = "block";
    // z.style.display = "block";
    // w.style.display = "block";
  }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= favicon_link_tag %>

    <link rel="stylesheet" href="https://db.onlinewebfonts.com/c/3def92f7b2ad644bd382798ecc8ca4c7?family=Canela" type="text/css"/>
    <script src="https://kit.fontawesome.com/56be5d596f.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="c-container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>

      <%= yield %>
    </div>
    <div class="c-footer">
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/moods/edit.html.erb
<section class="mood-edit">
  <div class="container">
    <div class="row mood-content">
      <div class="col-12">
      <div class="mood-edit-content">
        <h2 class="mood-edit-title">How are you feeling today?</h2>
          <%= simple_form_for(@mood) do |f| %>
          <%= f.input :mood_name, as: :radio_buttons, collection: ['😡', '😢', '😟', '😐', '🙂', '😍'], class: 'mood-radio-btn' %>
          <%= f.input :mood_notes, placeholder: 'I’m feeling great!!', id: 'mood-edit-input'%>
          <%= f.submit class:"mood-edit-btn"%>
          <% end %>
          <button class="mood-edit-btn mood-edit-btn-inverted"><%= link_to "Skip", days_path %></button>
          <button class="mood-edit-btn mood-edit-btn-inverted"><%= link_to "All logs", moods_path %></button>
      </div>
      </div>
    </div>
  </div>
</section>

app/views/moods/index.html.erb
<section class="mood-section">

  <div class="container mood-container">
    <div class="d-flex" id="mood-log">
      <h1 class="mood-log-text">Mood Log</h1>
    </div>
    <div class="moods-container">
    <div class="justify-content: flex-start"><h4 style="color: white; font-size: 24px;">Most recent</h4></div>
      <div class="mood-board">
        <% @moods.sort_by{ |mood| mood.id }.each do |mood|  %>
          <% if mood.mood_name != "#" %>
          <div class='task-row'>

            <div class="mood-date"><p style="color: #456fab;"><%= mood.day.calendar_date.strftime('%d %b %Y') %></p></div>

            <div class='mood-notes'>
              <% current_mood_id = mood.id %>
              <p style="color: #456fab;"><%= link_to mood.mood_notes, "moods/#{current_mood_id}/edit" %></p>
            </div>

            <div class='mood-emoji'>
              <p><%= link_to mood.mood_name, "moods/#{current_mood_id}/edit" %></p>
            </div>


          </div>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>

</section>

app/views/pages/index.html.erb
<h1>Hey guys, just putting some random bs in here ;) </h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<aside class="footer">
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-12">
					<ul class="footer-links">
            <li><%= link_to "Terms", "#", class: "footer-link" %></li>
            <li><%= link_to "Privacy", "#", class: "footer-link" %></li>
            <li><%= link_to "License", "#", class: "footer-link" %></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</aside>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="container">
    <div class="row">
      <div class="col-12 nav-container">
        <div class="navbar-title"><%= link_to "Clarity", root_path, class: "nav-title" %></div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "Dashboard", days_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "MoodLog", moods_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "About", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item nav-login">
              <% if !user_signed_in? %>
                <span class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link log-in" %>
                </span>
              <% else %>
                <span class="nav-item ">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link log-in" %>
                </span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/tasks/_task_form.html.erb
<%= simple_form_for [@day, @task] do |f| %>
  <%= f.input :title %>
  <div>
    <%= f.submit 'Submit', class: "btn btn-peach" %>
    <div class="btn btn-mid-blue">
      <%= link_to "Cancel", day_path(id: @day.id)%>
    </div>
    </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit Task</h1>
  <%= render "task_form", task: @task %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New Task</h1>
  <%= render "task_form", task: @task %>
</div>